pxdsResults = semanticseg(imds,trainednetTransfer, ...
    'MiniBatchSize',1, ...
    'WriteLocation','C:\Users\Max Kivits\Documents\MATLAB\Bacheloropdracht\Tests\test16Scratch\Labels', ...
    'Verbose',true);
 